version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
    - ./:/var/www/symfony:cached
    - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  nginx:
    image: nginx:latest
    ports:
    - '8080:80'
    volumes:
    - ./:/var/www/symfony:cached
    - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    restart: always